function outputPath = generateHTMLReport(allResults, config)
% GENERATEHTMLREPORT Export analysis as standalone HTML file with D3.js.
%   outputPath = generateHTMLReport(allResults, config)
%
%   Design follows 60/30/10 color rule:
%     60% — Dark canvas (#0a0a0f), panel backgrounds, neutral chrome
%     30% — Data visualization (dimension bars, heatmap, hotness curve)
%     10% — Hot accents (red dots, threshold, active states, gold highlights)
%
%   Color psychology: Each dimension mapped to a color with intentional meaning.

    if nargin < 2
        config = AnalysisConfig();
    end

    C = vizColors();

    rootDir = fileparts(fileparts(fileparts(mfilename('fullpath'))));
    outputPath = fullfile(rootDir, 'report.html');

    N = length(allResults);

    % Load metadata if available
    metaEntries = struct([]);
    try
        metaPath = fullfile(config.metadataDir, 'demo_tracks.json');
        if isfile(metaPath)
            metaEntries = loadMetadata(metaPath);
        end
    catch
    end

    % Prepare data for JSON embedding
    tracksJSON = struct();
    for i = 1:N
        tracksJSON(i).name = strrep(allResults(i).name, '_', ' ');
        tracksJSON(i).filename = allResults(i).name;
        tracksJSON(i).timeAxis = round(allResults(i).timeAxis, 3);
        tracksJSON(i).features = round(allResults(i).features, 4);
        tracksJSON(i).hotness = round(allResults(i).hotness, 4);
        tracksJSON(i).hotIdx = allResults(i).hotIdx;
        tracksJSON(i).numSegments = size(allResults(i).features, 2);
        tracksJSON(i).numHot = length(allResults(i).hotIdx);
        tracksJSON(i).duration = round(allResults(i).timeAxis(end), 1);

        % Per-dimension means
        tracksJSON(i).dimMeans = round(mean(allResults(i).features, 2)', 4);

        % Top 3 dominant dimensions
        meanFeat = mean(allResults(i).features, 2);
        [~, sortDims] = sort(meanFeat, 'descend');
        tracksJSON(i).topDims = sortDims(1:min(3,end))';

        % Metadata
        tracksJSON(i).artist = '';
        tracksJSON(i).genre = '';
        tracksJSON(i).bpm = 0;
        tracksJSON(i).origin = '';
        tracksJSON(i).key = '';
        tracksJSON(i).songwriters = '';
        tracksJSON(i).year = 0;
        if ~isempty(metaEntries)
            for m = 1:length(metaEntries)
                if contains(allResults(i).name, strrep(metaEntries(m).filename, '.wav', '')) || ...
                   strcmp(metaEntries(m).filename, allResults(i).name)
                    tracksJSON(i).artist = metaEntries(m).artist;
                    tracksJSON(i).genre = metaEntries(m).genre;
                    tracksJSON(i).bpm = metaEntries(m).bpm;
                    tracksJSON(i).origin = metaEntries(m).origin;
                    tracksJSON(i).key = metaEntries(m).key;
                    tracksJSON(i).year = metaEntries(m).year;
                    if iscell(metaEntries(m).songwriters)
                        tracksJSON(i).songwriters = strjoin(metaEntries(m).songwriters, ', ');
                    else
                        tracksJSON(i).songwriters = metaEntries(m).songwriters;
                    end
                    break;
                end
            end
        end
    end

    % Similarity matrix
    featureCell = {allResults.features};
    hotIdxCell = {allResults.hotIdx};
    simMatrix = buildSimilarityMatrix(featureCell, hotIdxCell);

    % Embed heatmap colormap anchors for D3
    heatmapAnchorsJSON = struct();
    heatmapAnchorsJSON.colors = round(C.heatmapAnchors, 4);
    heatmapAnchorsJSON.positions = C.heatmapPositions;

    simAnchorsJSON = struct();
    simAnchorsJSON.colors = round(C.simAnchors, 4);
    simAnchorsJSON.positions = C.simPositions;

    dataJSON = jsonencode(struct('tracks', tracksJSON, ...
        'simMatrix', round(simMatrix, 4), ...
        'dimensionNames', {config.dimensionNames}, ...
        'dimHex', {C.dimHex}, ...
        'heatmapAnchors', heatmapAnchorsJSON, ...
        'simAnchors', simAnchorsJSON));

    % Build HTML
    html = buildHTML(dataJSON);

    fid = fopen(outputPath, 'w');
    fprintf(fid, '%s', html);
    fclose(fid);

    fprintf('HTML report saved to: %s\n', outputPath);

    % Open in browser
    web(outputPath, '-browser');
end

function html = buildHTML(dataJSON)
    html = sprintf(['<!DOCTYPE html>\n' ...
'<html lang="en">\n' ...
'<head>\n' ...
'<meta charset="UTF-8">\n' ...
'<meta name="viewport" content="width=device-width, initial-scale=1.0">\n' ...
'<title>Dance Hit Audio Signature Report</title>\n' ...
'<script src="https://d3js.org/d3.v7.min.js"></script>\n' ...
'<style>\n' ...
'/* ============================================================\n' ...
'   60/30/10 Color Rule:\n' ...
'   60%% — #0a0a0f background, #111118 panels, #0e0e14 containers\n' ...
'   30%% — Dimension colors, heatmap data, chart elements\n' ...
'   10%% — Hot accents (#E91E63, #ff4444), gold highlights, active states\n' ...
'   ============================================================ */\n' ...
'* { margin:0; padding:0; box-sizing:border-box; }\n' ...
'body { background:#0a0a0f; color:#d0d0d0; font-family:"SF Mono",Monaco,"Fira Code",monospace; }\n' ...
'\n' ...
'/* --- Layout (60%% neutral) --- */\n' ...
'.app { display:flex; min-height:100vh; }\n' ...
'.sidebar { width:280px; background:#111118; border-right:1px solid #1a1a22; padding:20px 0; position:fixed; top:0; left:0; height:100vh; overflow-y:auto; z-index:10; }\n' ...
'.sidebar h2 { color:#E91E63; font-size:13px; padding:0 16px 12px; border-bottom:1px solid #1a1a22; margin-bottom:8px; letter-spacing:2px; text-transform:uppercase; }\n' ...
'.sidebar .nav-section { padding:8px 0; border-bottom:1px solid #141420; }\n' ...
'.sidebar .nav-section-title { color:#555; font-size:10px; padding:4px 16px; text-transform:uppercase; letter-spacing:1.5px; }\n' ...
'.sidebar .nav-item { display:block; padding:10px 16px; color:#777; text-decoration:none; font-size:12px; cursor:pointer; transition:all 0.15s; border-left:3px solid transparent; }\n' ...
'.sidebar .nav-item:hover { background:#16162a; color:#ccc; }\n' ...
'.sidebar .nav-item.active { background:#16162a; color:#E91E63; border-left-color:#E91E63; }\n' ...
'.sidebar .nav-item .nav-meta { color:#555; font-size:10px; margin-top:2px; }\n' ...
'.sidebar .nav-item .nav-dot { display:inline-block; width:8px; height:8px; border-radius:50%%; margin-right:6px; vertical-align:middle; }\n' ...
'.main { margin-left:280px; flex:1; padding:30px 40px; }\n' ...
'\n' ...
'/* --- Pages --- */\n' ...
'.page { display:none; }\n' ...
'.page.active { display:block; }\n' ...
'\n' ...
'/* --- Song header card --- */\n' ...
'.song-header { background:linear-gradient(135deg, #12121a 0%%, #1a1a2e 100%%); border:1px solid #2a2a3a; border-radius:12px; padding:24px 30px; margin-bottom:24px; }\n' ...
'.song-title { font-size:22px; font-weight:bold; color:#fff; margin-bottom:4px; }\n' ...
'.song-subtitle { color:#E91E63; font-size:14px; margin-bottom:16px; }\n' ...
'.song-meta-grid { display:grid; grid-template-columns:repeat(auto-fill, minmax(140px,1fr)); gap:12px; }\n' ...
'.meta-chip { background:#0f0f18; border:1px solid #2a2a3a; border-radius:8px; padding:10px 14px; }\n' ...
'.meta-chip .label { color:#555; font-size:9px; text-transform:uppercase; letter-spacing:1px; }\n' ...
'.meta-chip .value { color:#e0e0e0; font-size:15px; font-weight:bold; margin-top:2px; }\n' ...
'.meta-chip .value.accent { color:#E91E63; }\n' ...
'\n' ...
'/* --- Stats row --- */\n' ...
'.stats-row { display:flex; gap:16px; margin:20px 0; flex-wrap:wrap; }\n' ...
'.stat-card { background:#111118; border:1px solid #1a1a22; border-radius:8px; padding:14px 18px; min-width:120px; }\n' ...
'.stat-card .val { font-size:24px; font-weight:bold; }\n' ...
'.stat-card .lbl { font-size:10px; color:#555; margin-top:3px; text-transform:uppercase; letter-spacing:0.5px; }\n' ...
'\n' ...
'/* --- Dimension bars (30%% data color) --- */\n' ...
'.dim-bars { margin:20px 0; }\n' ...
'.dim-bar-row { display:flex; align-items:center; margin:6px 0; }\n' ...
'.dim-bar-swatch { width:12px; height:12px; border-radius:3px; margin-right:8px; flex-shrink:0; }\n' ...
'.dim-bar-label { width:140px; font-size:11px; color:#888; text-align:right; padding-right:12px; }\n' ...
'.dim-bar-track { flex:1; background:#0e0e14; border-radius:4px; height:20px; overflow:hidden; position:relative; }\n' ...
'.dim-bar-fill { height:100%%; border-radius:4px; transition:width 0.4s ease; }\n' ...
'.dim-bar-val { width:50px; font-size:11px; color:#aaa; padding-left:8px; }\n' ...
'.dim-bar-psych { width:130px; font-size:9px; color:#555; font-style:italic; padding-left:4px; }\n' ...
'\n' ...
'/* --- Viz containers --- */\n' ...
'.viz-container { background:#0e0e14; border:1px solid #1a1a22; border-radius:8px; padding:20px; margin:16px 0; overflow-x:auto; }\n' ...
'.viz-title { color:#777; font-size:12px; margin-bottom:12px; text-transform:uppercase; letter-spacing:1.5px; }\n' ...
'\n' ...
'/* --- Legend components --- */\n' ...
'.legend-row { display:flex; align-items:flex-start; gap:30px; margin:16px 0; flex-wrap:wrap; }\n' ...
'.legend-gradient { display:flex; flex-direction:column; align-items:center; }\n' ...
'.legend-gradient-bar { width:200px; height:14px; border-radius:3px; }\n' ...
'.legend-gradient-labels { display:flex; justify-content:space-between; width:200px; margin-top:4px; }\n' ...
'.legend-gradient-labels span { font-size:9px; color:#666; }\n' ...
'.legend-gradient-title { font-size:10px; color:#777; margin-bottom:4px; text-transform:uppercase; letter-spacing:1px; }\n' ...
'.dim-legend { display:grid; grid-template-columns:repeat(4, 1fr); gap:6px 16px; }\n' ...
'.dim-legend-item { display:flex; align-items:center; gap:6px; }\n' ...
'.dim-legend-dot { width:10px; height:10px; border-radius:2px; flex-shrink:0; }\n' ...
'.dim-legend-name { font-size:10px; color:#aaa; }\n' ...
'.dim-legend-psych { font-size:8px; color:#555; font-style:italic; }\n' ...
'\n' ...
'/* --- System overview --- */\n' ...
'h1.page-title { color:#E91E63; font-size:20px; margin-bottom:6px; }\n' ...
'.page-subtitle { color:#555; font-size:12px; margin-bottom:20px; font-style:italic; }\n' ...
'.overview-grid { display:grid; grid-template-columns:repeat(auto-fill, minmax(300px,1fr)); gap:16px; margin:20px 0; }\n' ...
'.overview-card { background:#111118; border:1px solid #1a1a22; border-radius:10px; padding:18px; cursor:pointer; transition:all 0.2s; }\n' ...
'.overview-card:hover { border-color:#E91E63; transform:translateY(-2px); box-shadow:0 4px 20px rgba(233,30,99,0.1); }\n' ...
'.overview-card .oc-title { color:#fff; font-size:14px; font-weight:bold; margin-bottom:4px; }\n' ...
'.overview-card .oc-genre { color:#E91E63; font-size:11px; }\n' ...
'.overview-card .oc-stats { color:#555; font-size:10px; margin-top:8px; }\n' ...
'.overview-card .oc-bar-row { display:flex; gap:2px; margin-top:10px; height:8px; }\n' ...
'.overview-card .oc-bar-seg { flex:1; border-radius:2px; }\n' ...
'</style>\n' ...
'</head>\n' ...
'<body>\n' ...
'<div class="app">\n' ...
'  <nav class="sidebar" id="sidebar"></nav>\n' ...
'  <div class="main" id="main"></div>\n' ...
'</div>\n' ...
'\n' ...
'<script>\n' ...
'const DATA = %s;\n' ...
'const DIM_NAMES = DATA.dimensionNames;\n' ...
'const DIM_COLORS = DATA.dimHex;\n' ...
'\n' ...
'// Color psychology rationale for each dimension\n' ...
'const DIM_PSYCH = [\n' ...
'  "Trust & Reliability",\n' ...
'  "Power & Primal Force",\n' ...
'  "Human Warmth & Emotion",\n' ...
'  "Impact & Urgency",\n' ...
'  "Change & Movement",\n' ...
'  "Sophistication & Depth",\n' ...
'  "Organic Fullness & Balance",\n' ...
'  "Contrast & Drama"\n' ...
'];\n' ...
'\n' ...
'// Dimension categories for visual grouping\n' ...
'const DIM_CATEGORIES = [\n' ...
'  { name: "RHYTHM", desc: "beat · tempo · groove", dims: [0, 3, 5] },\n' ...
'  { name: "TONAL", desc: "bass · voice · harmonics", dims: [1, 2, 6] },\n' ...
'  { name: "TEXTURE", desc: "flux · dynamics", dims: [4, 7] }\n' ...
'];\n' ...
'\n' ...
'// Build perceptual heatmap colormap from anchor points\n' ...
'function buildColorScale(anchors, positions) {\n' ...
'  const stops = positions.map((p, i) => {\n' ...
'    const c = anchors[i];\n' ...
'    return { pos: p, color: `rgb(${Math.round(c[0]*255)},${Math.round(c[1]*255)},${Math.round(c[2]*255)})` };\n' ...
'  });\n' ...
'  return d3.scaleLinear()\n' ...
'    .domain(stops.map(s => s.pos))\n' ...
'    .range(stops.map(s => s.color))\n' ...
'    .interpolate(d3.interpolateRgb);\n' ...
'}\n' ...
'\n' ...
'const heatmapColor = buildColorScale(\n' ...
'  DATA.heatmapAnchors.colors,\n' ...
'  DATA.heatmapAnchors.positions\n' ...
');\n' ...
'const simColor = buildColorScale(\n' ...
'  DATA.simAnchors.colors,\n' ...
'  DATA.simAnchors.positions\n' ...
');\n' ...
'\n' ...
'// ---- Build sidebar ----\n' ...
'(function(){\n' ...
'  const sb = document.getElementById("sidebar");\n' ...
'  sb.innerHTML = `<h2>Audio Signatures</h2>`;\n' ...
'\n' ...
'  const sysSection = document.createElement("div");\n' ...
'  sysSection.className = "nav-section";\n' ...
'  sysSection.innerHTML = `<div class="nav-section-title">System</div>`;\n' ...
'  const sysItem = document.createElement("div");\n' ...
'  sysItem.className = "nav-item active";\n' ...
'  sysItem.dataset.page = "system";\n' ...
'  sysItem.innerHTML = `All Tracks Overview`;\n' ...
'  sysItem.onclick = () => showPage("system");\n' ...
'  sysSection.appendChild(sysItem);\n' ...
'\n' ...
'  const simItem = document.createElement("div");\n' ...
'  simItem.className = "nav-item";\n' ...
'  simItem.dataset.page = "similarity";\n' ...
'  simItem.innerHTML = `Similarity Matrix`;\n' ...
'  simItem.onclick = () => showPage("similarity");\n' ...
'  sysSection.appendChild(simItem);\n' ...
'\n' ...
'  const legendItem = document.createElement("div");\n' ...
'  legendItem.className = "nav-item";\n' ...
'  legendItem.dataset.page = "color-key";\n' ...
'  legendItem.innerHTML = `Color Psychology Key`;\n' ...
'  legendItem.onclick = () => showPage("color-key");\n' ...
'  sysSection.appendChild(legendItem);\n' ...
'  sb.appendChild(sysSection);\n' ...
'\n' ...
'  // Individual songs with colored dots\n' ...
'  const songSection = document.createElement("div");\n' ...
'  songSection.className = "nav-section";\n' ...
'  songSection.innerHTML = `<div class="nav-section-title">Individual Songs</div>`;\n' ...
'  DATA.tracks.forEach((t, i) => {\n' ...
'    const item = document.createElement("div");\n' ...
'    item.className = "nav-item";\n' ...
'    item.dataset.page = "song-" + i;\n' ...
'    const topDim = (t.topDims && t.topDims.length > 0) ? t.topDims[0] - 1 : 0;\n' ...
'    const dotColor = DIM_COLORS[topDim] || "#E91E63";\n' ...
'    const shortName = t.name.replace(/demo track \\d+ /i, "");\n' ...
'    item.innerHTML = `<div><span class="nav-dot" style="background:${dotColor}"></span>${shortName}</div><div class="nav-meta">${t.artist || "Track "+(i+1)} &middot; ${t.genre || ""}</div>`;\n' ...
'    item.onclick = () => showPage("song-" + i);\n' ...
'    songSection.appendChild(item);\n' ...
'  });\n' ...
'  sb.appendChild(songSection);\n' ...
'})();\n' ...
'\n' ...
'// ---- Page navigation ----\n' ...
'function showPage(id) {\n' ...
'  document.querySelectorAll(".page").forEach(p => p.classList.remove("active"));\n' ...
'  document.querySelectorAll(".nav-item").forEach(n => n.classList.remove("active"));\n' ...
'  const page = document.getElementById("page-" + id);\n' ...
'  if (page) page.classList.add("active");\n' ...
'  const nav = document.querySelector(`.nav-item[data-page="${id}"]`);\n' ...
'  if (nav) nav.classList.add("active");\n' ...
'}\n' ...
'\n' ...
'const main = document.getElementById("main");\n' ...
'\n' ...
'// Helper: build dimension legend HTML\n' ...
'function dimLegendHTML() {\n' ...
'  let html = `<div class="dim-legend">`;\n' ...
'  DIM_NAMES.forEach((name, i) => {\n' ...
'    html += `<div class="dim-legend-item">\n' ...
'      <div class="dim-legend-dot" style="background:${DIM_COLORS[i]}"></div>\n' ...
'      <div><div class="dim-legend-name">${name}</div><div class="dim-legend-psych">${DIM_PSYCH[i]}</div></div>\n' ...
'    </div>`;\n' ...
'  });\n' ...
'  html += `</div>`;\n' ...
'  return html;\n' ...
'}\n' ...
'\n' ...
'// ---- SYSTEM OVERVIEW PAGE ----\n' ...
'(function(){\n' ...
'  const page = document.createElement("div");\n' ...
'  page.id = "page-system"; page.className = "page active";\n' ...
'  let html = `<h1 class="page-title">All Tracks Overview</h1>`;\n' ...
'  html += `<div class="page-subtitle">60/30/10 design: neutral canvas (60%%), data visualization (30%%), hot accents (10%%)</div>`;\n' ...
'  html += dimLegendHTML();\n' ...
'  html += `<div class="overview-grid">`;\n' ...
'  DATA.tracks.forEach((t, i) => {\n' ...
'    const hotPct = (100*t.numHot/t.numSegments).toFixed(0);\n' ...
'    const shortName = t.name.replace(/demo track \\d+ /i, "");\n' ...
'    let bars = "";\n' ...
'    t.dimMeans.forEach((v, d) => {\n' ...
'      const opacity = (0.3 + v*0.7).toFixed(2);\n' ...
'      bars += `<div class="oc-bar-seg" style="background:${DIM_COLORS[d]};opacity:${opacity}"></div>`;\n' ...
'    });\n' ...
'    html += `<div class="overview-card" onclick="showPage(''song-${i}'')">\n' ...
'      <div class="oc-title">${shortName}</div>\n' ...
'      <div class="oc-genre">${t.artist} &middot; ${t.genre}</div>\n' ...
'      <div class="oc-stats">${t.numSegments} segments &middot; ${t.numHot} hot (${hotPct}%%) &middot; ${t.duration}s &middot; ${t.bpm} BPM</div>\n' ...
'      <div class="oc-bar-row">${bars}</div>\n' ...
'    </div>`;\n' ...
'  });\n' ...
'  html += `</div>`;\n' ...
'  page.innerHTML = html;\n' ...
'  main.appendChild(page);\n' ...
'})();\n' ...
'\n' ...
'// ---- COLOR PSYCHOLOGY KEY PAGE ----\n' ...
'(function(){\n' ...
'  const page = document.createElement("div");\n' ...
'  page.id = "page-color-key"; page.className = "page";\n' ...
'  let html = `<h1 class="page-title">Color Psychology Key</h1>`;\n' ...
'  html += `<div class="page-subtitle">Every color choice is intentional. Each dimension maps to a color that communicates its perceptual meaning.</div>`;\n' ...
'\n' ...
'  // Dimension color cards\n' ...
'  html += `<div style="display:grid;grid-template-columns:repeat(2,1fr);gap:16px;margin:24px 0;">`;\n' ...
'  const descriptions = [\n' ...
'    "Steel Blue evokes trust, reliability, and steadiness — perfect for BPM stability, the rhythmic foundation you can count on.",\n' ...
'    "Deep Crimson conveys power, physical force, and primal energy — the visceral low-end punch that moves bodies.",\n' ...
'    "Warm Amber represents human warmth and emotional connection — the voice that bridges artist and listener.",\n' ...
'    "Burnt Orange signals impact, urgency, and percussive action — the transient attacks that drive momentum.",\n' ...
'    "Electric Cyan symbolizes change, movement, and transformation — the spectral shifts that keep ears engaged.",\n' ...
'    "Deep Purple suggests sophistication, layered complexity, and depth — intricate rhythmic patterns within patterns.",\n' ...
'    "Emerald Green reflects organic fullness and tonal balance — the rich harmonic spectrum of natural sound.",\n' ...
'    "Hot Magenta embodies contrast, drama, and extremes — the dynamic peaks and valleys that create excitement."\n' ...
'  ];\n' ...
'  DIM_NAMES.forEach((name, i) => {\n' ...
'    html += `<div style="background:#111118;border:1px solid #1a1a22;border-radius:10px;padding:20px;border-left:4px solid ${DIM_COLORS[i]};">\n' ...
'      <div style="font-size:14px;font-weight:bold;color:${DIM_COLORS[i]};margin-bottom:4px;">${name}</div>\n' ...
'      <div style="font-size:10px;color:#E91E63;text-transform:uppercase;letter-spacing:1px;margin-bottom:8px;">${DIM_PSYCH[i]}</div>\n' ...
'      <div style="font-size:11px;color:#888;line-height:1.5;">${descriptions[i]}</div>\n' ...
'    </div>`;\n' ...
'  });\n' ...
'  html += `</div>`;\n' ...
'\n' ...
'  // Heatmap gradient legend\n' ...
'  html += `<div class="viz-container"><div class="viz-title">Heatmap Color Scale</div>\n' ...
'    <div style="display:flex;align-items:center;gap:20px;">\n' ...
'      <div id="heatmap-gradient-key" style="flex:1;height:30px;border-radius:4px;"></div>\n' ...
'      <div style="font-size:10px;color:#666;width:200px;">Custom perceptual colormap: deep navy (silence) → indigo → teal → amber → vermilion → near-white (peak energy)</div>\n' ...
'    </div>\n' ...
'    <div style="display:flex;justify-content:space-between;margin-top:6px;font-size:9px;color:#666;">\n' ...
'      <span>0.0 Silent</span><span>0.25 Low</span><span>0.50 Moderate</span><span>0.75 High</span><span>1.0 Peak</span>\n' ...
'    </div>\n' ...
'  </div>`;\n' ...
'\n' ...
'  // Similarity gradient legend\n' ...
'  html += `<div class="viz-container"><div class="viz-title">Similarity Color Scale</div>\n' ...
'    <div style="display:flex;align-items:center;gap:20px;">\n' ...
'      <div id="sim-gradient-key" style="flex:1;height:30px;border-radius:4px;"></div>\n' ...
'      <div style="font-size:10px;color:#666;width:200px;">Slate charcoal (distant) → muted navy → teal → olive gold → warm gold (identical signatures)</div>\n' ...
'    </div>\n' ...
'    <div style="display:flex;justify-content:space-between;margin-top:6px;font-size:9px;color:#666;">\n' ...
'      <span>0.0 Distant</span><span>0.3</span><span>0.5 Moderate</span><span>0.7</span><span>1.0 Identical</span>\n' ...
'    </div>\n' ...
'  </div>`;\n' ...
'\n' ...
'  // 60/30/10 explanation\n' ...
'  html += `<div class="viz-container"><div class="viz-title">Design Philosophy: 60/30/10 Rule</div>\n' ...
'    <div style="display:flex;gap:16px;margin-top:8px;">\n' ...
'      <div style="flex:6;background:#0a0a0f;border:1px solid #1a1a22;border-radius:8px;padding:16px;text-align:center;">\n' ...
'        <div style="font-size:28px;font-weight:bold;color:#555;">60%%</div>\n' ...
'        <div style="font-size:10px;color:#555;margin-top:4px;">NEUTRAL CANVAS</div>\n' ...
'        <div style="font-size:9px;color:#444;margin-top:4px;">Background, panels, grid, whitespace</div>\n' ...
'      </div>\n' ...
'      <div style="flex:3;background:linear-gradient(135deg,${DIM_COLORS[0]},${DIM_COLORS[4]});border-radius:8px;padding:16px;text-align:center;">\n' ...
'        <div style="font-size:28px;font-weight:bold;color:#fff;">30%%</div>\n' ...
'        <div style="font-size:10px;color:rgba(255,255,255,0.8);margin-top:4px;">DATA COLORS</div>\n' ...
'        <div style="font-size:9px;color:rgba(255,255,255,0.6);margin-top:4px;">Heatmap, bars, charts, dimension colors</div>\n' ...
'      </div>\n' ...
'      <div style="flex:1;background:#E91E63;border-radius:8px;padding:16px;text-align:center;">\n' ...
'        <div style="font-size:28px;font-weight:bold;color:#fff;">10%%</div>\n' ...
'        <div style="font-size:10px;color:rgba(255,255,255,0.8);margin-top:4px;">ACCENTS</div>\n' ...
'        <div style="font-size:9px;color:rgba(255,255,255,0.6);margin-top:4px;">Hot markers, thresholds</div>\n' ...
'      </div>\n' ...
'    </div>\n' ...
'  </div>`;\n' ...
'\n' ...
'  page.innerHTML = html;\n' ...
'  main.appendChild(page);\n' ...
'\n' ...
'  // Render gradient bars\n' ...
'  setTimeout(() => {\n' ...
'    renderGradientBar("heatmap-gradient-key", heatmapColor);\n' ...
'    renderGradientBar("sim-gradient-key", simColor);\n' ...
'  }, 50);\n' ...
'})();\n' ...
'\n' ...
'function renderGradientBar(containerId, colorScale) {\n' ...
'  const container = document.getElementById(containerId);\n' ...
'  if (!container) return;\n' ...
'  const w = container.clientWidth || 600;\n' ...
'  const h = 30;\n' ...
'  const canvas = document.createElement("canvas");\n' ...
'  canvas.width = w; canvas.height = h;\n' ...
'  canvas.style.width = "100%%"; canvas.style.height = h+"px"; canvas.style.borderRadius = "4px";\n' ...
'  const ctx = canvas.getContext("2d");\n' ...
'  for (let x = 0; x < w; x++) {\n' ...
'    ctx.fillStyle = colorScale(x / w);\n' ...
'    ctx.fillRect(x, 0, 1, h);\n' ...
'  }\n' ...
'  container.appendChild(canvas);\n' ...
'}\n' ...
'\n' ...
'// ---- SIMILARITY MATRIX PAGE ----\n' ...
'(function(){\n' ...
'  const page = document.createElement("div");\n' ...
'  page.id = "page-similarity"; page.className = "page";\n' ...
'  page.innerHTML = `<h1 class="page-title">Cross-Song Similarity Matrix</h1>\n' ...
'    <div class="page-subtitle">Cosine similarity between mean hot-segment feature vectors</div>\n' ...
'    <div class="legend-row">\n' ...
'      <div class="legend-gradient">\n' ...
'        <div class="legend-gradient-title">Similarity Scale</div>\n' ...
'        <div id="sim-legend-bar" class="legend-gradient-bar"></div>\n' ...
'        <div class="legend-gradient-labels"><span>0.0 Distant</span><span>0.5 Moderate</span><span>1.0 Identical</span></div>\n' ...
'      </div>\n' ...
'    </div>\n' ...
'    <div id="sim-matrix-container" class="viz-container"></div>`;\n' ...
'  main.appendChild(page);\n' ...
'\n' ...
'  setTimeout(() => {\n' ...
'    renderGradientBar("sim-legend-bar", simColor);\n' ...
'    const sim = DATA.simMatrix;\n' ...
'    const n = sim.length;\n' ...
'    const cellSize = 56;\n' ...
'    const margin = {top:10, left:160, right:20, bottom:80};\n' ...
'    const w = cellSize*n + margin.left + margin.right;\n' ...
'    const h = cellSize*n + margin.top + margin.bottom;\n' ...
'    const svg = d3.select("#sim-matrix-container").append("svg").attr("width",w).attr("height",h);\n' ...
'    const g = svg.append("g").attr("transform",`translate(${margin.left},${margin.top})`);\n' ...
'    const names = DATA.tracks.map(t => t.name.replace(/demo track \\d+ /i,""));\n' ...
'    for(let i=0;i<n;i++){\n' ...
'      for(let j=0;j<n;j++){\n' ...
'        g.append("rect").attr("x",j*cellSize).attr("y",i*cellSize)\n' ...
'          .attr("width",cellSize).attr("height",cellSize)\n' ...
'          .attr("fill",simColor(sim[i][j])).attr("stroke","#0a0a0f").attr("stroke-width",1).attr("rx",2)\n' ...
'          .style("cursor","pointer")\n' ...
'          .on("click", () => { if(i!==j) showPage("song-"+i); });\n' ...
'        const brightness = sim[i][j] > 0.6 ? "#111" : "#eee";\n' ...
'        g.append("text").attr("x",j*cellSize+cellSize/2).attr("y",i*cellSize+cellSize/2+4)\n' ...
'          .attr("text-anchor","middle").attr("fill",brightness)\n' ...
'          .attr("font-size","10px").attr("font-weight","bold").text(sim[i][j].toFixed(2));\n' ...
'      }\n' ...
'      g.append("text").attr("x",-8).attr("y",i*cellSize+cellSize/2+4)\n' ...
'        .attr("text-anchor","end").attr("fill","#aaa").attr("font-size","10px").text(names[i]);\n' ...
'      g.append("text").attr("x",i*cellSize+cellSize/2).attr("y",n*cellSize+14)\n' ...
'        .attr("text-anchor","end").attr("fill","#aaa").attr("font-size","10px")\n' ...
'        .attr("transform",`rotate(-50,${i*cellSize+cellSize/2},${n*cellSize+14})`).text(names[i]);\n' ...
'    }\n' ...
'  }, 100);\n' ...
'})();\n' ...
'\n' ...
'// ---- INDIVIDUAL SONG PAGES ----\n' ...
'DATA.tracks.forEach((track, idx) => {\n' ...
'  const page = document.createElement("div");\n' ...
'  page.id = "page-song-" + idx;\n' ...
'  page.className = "page";\n' ...
'  const shortName = track.name.replace(/demo track \\d+ /i, "");\n' ...
'  const hotPct = (100*track.numHot/track.numSegments).toFixed(1);\n' ...
'\n' ...
'  // Song header card\n' ...
'  let html = `<div class="song-header">\n' ...
'    <div class="song-title">${shortName}</div>\n' ...
'    <div class="song-subtitle">${track.artist || "Unknown Artist"} &middot; ${track.genre || "Unknown Genre"} &middot; ${track.origin || ""}</div>\n' ...
'    <div class="song-meta-grid">\n' ...
'      <div class="meta-chip"><div class="label">BPM</div><div class="value accent">${track.bpm || "?"}</div></div>\n' ...
'      <div class="meta-chip"><div class="label">Key</div><div class="value">${track.key || "?"}</div></div>\n' ...
'      <div class="meta-chip"><div class="label">Duration</div><div class="value">${track.duration}s</div></div>\n' ...
'      <div class="meta-chip"><div class="label">Segments</div><div class="value">${track.numSegments}</div></div>\n' ...
'      <div class="meta-chip"><div class="label">Hot Segments</div><div class="value accent">${track.numHot} (${hotPct}%%)</div></div>\n' ...
'      <div class="meta-chip"><div class="label">Year</div><div class="value">${track.year || "?"}</div></div>\n' ...
'      <div class="meta-chip"><div class="label">Songwriters</div><div class="value">${track.songwriters || "?"}</div></div>\n' ...
'    </div>\n' ...
'  </div>`;\n' ...
'\n' ...
'  // Top dimensions with colored stat cards (10%% accent)\n' ...
'  html += `<div class="stats-row">`;\n' ...
'  const topDims = track.topDims || [];\n' ...
'  topDims.forEach((di, rank) => {\n' ...
'    const dIdx = di - 1;\n' ...
'    if (dIdx >= 0 && dIdx < 8) {\n' ...
'      html += `<div class="stat-card" style="border-left:3px solid ${DIM_COLORS[dIdx]};">\n' ...
'        <div class="val" style="color:${DIM_COLORS[dIdx]}">#${rank+1}</div>\n' ...
'        <div class="lbl">${DIM_NAMES[dIdx]}</div>\n' ...
'        <div style="font-size:8px;color:#555;font-style:italic;margin-top:2px;">${DIM_PSYCH[dIdx]}</div>\n' ...
'      </div>`;\n' ...
'    }\n' ...
'  });\n' ...
'  html += `</div>`;\n' ...
'\n' ...
'  // Dimension bars grouped by category: RHYTHM → TONAL → TEXTURE\n' ...
'  html += `<div class="dim-bars">`;\n' ...
'  DIM_CATEGORIES.forEach(cat => {\n' ...
'    html += `<div style="font-size:10px;color:#555;text-transform:uppercase;letter-spacing:1.5px;margin:14px 0 6px 162px;border-bottom:1px solid #1a1a22;padding-bottom:4px;">${cat.name} <span style="font-weight:normal;color:#444;letter-spacing:0;">${cat.desc}</span></div>`;\n' ...
'    cat.dims.forEach(d => {\n' ...
'      const v = track.dimMeans[d];\n' ...
'      const pct = (v * 100).toFixed(0);\n' ...
'      html += `<div class="dim-bar-row">\n' ...
'        <div class="dim-bar-swatch" style="background:${DIM_COLORS[d]}"></div>\n' ...
'        <div class="dim-bar-label">${DIM_NAMES[d]}</div>\n' ...
'        <div class="dim-bar-track"><div class="dim-bar-fill" style="width:${pct}%%;background:${DIM_COLORS[d]}"></div></div>\n' ...
'        <div class="dim-bar-val">${v.toFixed(2)}</div>\n' ...
'        <div class="dim-bar-psych">${DIM_PSYCH[d]}</div>\n' ...
'      </div>`;\n' ...
'    });\n' ...
'  });\n' ...
'  html += `</div>`;\n' ...
'\n' ...
'  // Heatmap with legend\n' ...
'  html += `<div class="viz-container">\n' ...
'    <div class="viz-title">FINGERPRINT &mdash; 8 dimensions · rhythm · tonal · texture &nbsp;|&nbsp; brighter = higher</div>\n' ...
'    <div class="legend-row">\n' ...
'      <div class="legend-gradient">\n' ...
'        <div class="legend-gradient-title">Intensity</div>\n' ...
'        <div id="heatmap-legend-${idx}" class="legend-gradient-bar"></div>\n' ...
'        <div class="legend-gradient-labels"><span>Silent</span><span>Low</span><span>Mid</span><span>High</span><span>Peak</span></div>\n' ...
'      </div>\n' ...
'    </div>\n' ...
'    <div id="heatmap-${idx}"></div>\n' ...
'  </div>`;\n' ...
'\n' ...
'  // Hotness chart\n' ...
'  html += `<div class="viz-container">\n' ...
'    <div class="viz-title">HOTNESS &mdash; all dimensions &rarr; single score &nbsp;|&nbsp; above threshold = hot segment</div>\n' ...
'    <div style="display:flex;gap:16px;margin-bottom:8px;font-size:10px;">\n' ...
'      <div style="display:flex;align-items:center;gap:4px;"><div style="width:20px;height:2px;background:#3B82C4;"></div><span style="color:#666;">Hotness curve</span></div>\n' ...
'      <div style="display:flex;align-items:center;gap:4px;"><div style="width:20px;height:2px;background:#E91E63;border-top:1px dashed #E91E63;"></div><span style="color:#666;">Hot threshold</span></div>\n' ...
'      <div style="display:flex;align-items:center;gap:4px;"><div style="width:8px;height:8px;border-radius:50%%;background:#E91E63;"></div><span style="color:#666;">Hot segment</span></div>\n' ...
'    </div>\n' ...
'    <div id="hotness-${idx}"></div>\n' ...
'  </div>`;\n' ...
'\n' ...
'  page.innerHTML = html;\n' ...
'  main.appendChild(page);\n' ...
'\n' ...
'  setTimeout(() => {\n' ...
'    renderGradientBar("heatmap-legend-" + idx, heatmapColor);\n' ...
'    renderSongViz(idx);\n' ...
'  }, 100);\n' ...
'});\n' ...
'\n' ...
'function renderSongViz(idx) {\n' ...
'  const track = DATA.tracks[idx];\n' ...
'  const features = track.features;\n' ...
'  const timeAxis = track.timeAxis;\n' ...
'  const hotness = track.hotness;\n' ...
'  const N = track.numSegments;\n' ...
'  const hotSet = new Set(track.hotIdx.map(h => h-1));\n' ...
'\n' ...
'  // --- Heatmap (30%% data color) reordered by category ---\n' ...
'  const dispOrder = [0,3,5, 1,2,6, 4,7]; // RHYTHM, TONAL, TEXTURE\n' ...
'  const cellW = Math.max(3, Math.min(10, 900/N));\n' ...
'  const cellH = 28;\n' ...
'  const margin = {top:5, right:20, bottom:30, left:140};\n' ...
'  const w = cellW*N + margin.left + margin.right;\n' ...
'  const h = cellH*8 + margin.top + margin.bottom;\n' ...
'\n' ...
'  const svg = d3.select("#heatmap-"+idx).append("svg").attr("width",w).attr("height",h);\n' ...
'  const g = svg.append("g").attr("transform",`translate(${margin.left},${margin.top})`);\n' ...
'\n' ...
'  for(let row=0; row<8; row++){\n' ...
'    const d = dispOrder[row]; // original dimension index\n' ...
'    for(let s=0; s<N; s++){\n' ...
'      g.append("rect")\n' ...
'        .attr("x", s*cellW).attr("y",(7-row)*cellH)\n' ...
'        .attr("width",cellW).attr("height",cellH)\n' ...
'        .attr("fill", heatmapColor(features[d][s]))\n' ...
'        .attr("stroke","none");\n' ...
'      if(hotSet.has(s)){\n' ...
'        g.append("rect").attr("x",s*cellW).attr("y",(7-row)*cellH)\n' ...
'          .attr("width",cellW).attr("height",cellH)\n' ...
'          .attr("fill","rgba(32,230,64,0.12)").attr("stroke","none");\n' ...
'      }\n' ...
'    }\n' ...
'    // Dimension labels colored by psychology mapping\n' ...
'    g.append("text").attr("x",-6).attr("y",(7-row)*cellH+cellH/2+4)\n' ...
'      .attr("text-anchor","end").attr("fill",DIM_COLORS[d]).attr("font-size","11px").attr("font-weight","bold")\n' ...
'      .text(DIM_NAMES[d]);\n' ...
'  }\n' ...
'  // Category separator lines\n' ...
'  [3,6].forEach(bnd => {\n' ...
'    const y = (8-bnd)*cellH;\n' ...
'    g.append("line").attr("x1",0).attr("x2",cellW*N).attr("y1",y).attr("y2",y)\n' ...
'      .attr("stroke","rgba(255,255,255,0.3)").attr("stroke-width",1.5);\n' ...
'  });\n' ...
'  // Category labels\n' ...
'  [{y:1.5,t:"RHYTHM"},{y:4.5,t:"TONAL"},{y:6.5,t:"TEXTURE"}].forEach(c => {\n' ...
'    g.append("text").attr("x",3).attr("y",(8-c.y)*cellH-2)\n' ...
'      .attr("fill","rgba(255,255,255,0.3)").attr("font-size","8px").attr("font-weight","bold")\n' ...
'      .text(c.t);\n' ...
'  });\n' ...
'\n' ...
'  // Time axis\n' ...
'  const xScale = d3.scaleLinear().domain([0,N-1]).range([0,cellW*N]);\n' ...
'  const tickCount = Math.min(12, N);\n' ...
'  for(let t=0; t<tickCount; t++){\n' ...
'    const si = Math.floor(t * N / tickCount);\n' ...
'    if(si < timeAxis.length){\n' ...
'      g.append("text").attr("x", xScale(si)).attr("y", 8*cellH+14)\n' ...
'        .attr("text-anchor","middle").attr("fill","#555").attr("font-size","9px")\n' ...
'        .text(timeAxis[si].toFixed(1)+"s");\n' ...
'    }\n' ...
'  }\n' ...
'\n' ...
'  // --- Hotness chart ---\n' ...
'  const hcMargin = {top:10, right:30, bottom:30, left:140};\n' ...
'  const hcW = w;\n' ...
'  const hcH = 160;\n' ...
'  const hcSvg = d3.select("#hotness-"+idx).append("svg").attr("width",hcW).attr("height",hcH);\n' ...
'  const hcG = hcSvg.append("g").attr("transform",`translate(${hcMargin.left},${hcMargin.top})`);\n' ...
'  const chartW = cellW * N;\n' ...
'  const chartH = hcH - hcMargin.top - hcMargin.bottom;\n' ...
'\n' ...
'  const hxScale = d3.scaleLinear().domain([0,N-1]).range([0,chartW]);\n' ...
'  const hyScale = d3.scaleLinear().domain([d3.min(hotness)*0.9, d3.max(hotness)*1.1]).range([chartH,0]);\n' ...
'\n' ...
'  // Cool zone background fill (60%% neutral)\n' ...
'  hcG.append("rect").attr("x",0).attr("y",0).attr("width",chartW).attr("height",chartH)\n' ...
'    .attr("fill","#0c0c16").attr("rx",4);\n' ...
'\n' ...
'  // Threshold line (10%% accent)\n' ...
'  const mean = d3.mean(hotness);\n' ...
'  const std = d3.deviation(hotness) || 0;\n' ...
'  const thresh = mean + std;\n' ...
'  hcG.append("line").attr("x1",0).attr("x2",chartW).attr("y1",hyScale(thresh)).attr("y2",hyScale(thresh))\n' ...
'    .attr("stroke","#E91E63").attr("stroke-dasharray","6,3").attr("stroke-width",1);\n' ...
'  hcG.append("text").attr("x",chartW+4).attr("y",hyScale(thresh)+4)\n' ...
'    .attr("fill","#E91E63").attr("font-size","9px").text("HOT");\n' ...
'\n' ...
'  // Fill area above threshold (10%% accent fill)\n' ...
'  const areaAbove = d3.area()\n' ...
'    .x((d,i) => hxScale(i))\n' ...
'    .y0(d => hyScale(Math.min(d, thresh)))\n' ...
'    .y1(d => hyScale(d))\n' ...
'    .curve(d3.curveMonotoneX);\n' ...
'  hcG.append("path").datum(hotness).attr("d",areaAbove)\n' ...
'    .attr("fill","rgba(233,30,99,0.08)").attr("stroke","none");\n' ...
'\n' ...
'  // Hotness line (30%% data)\n' ...
'  const line = d3.line().x((d,i) => hxScale(i)).y(d => hyScale(d)).curve(d3.curveMonotoneX);\n' ...
'  hcG.append("path").datum(hotness).attr("d",line).attr("fill","none").attr("stroke","#3B82C4").attr("stroke-width",1.5);\n' ...
'\n' ...
'  // Hot dots (10%% accent)\n' ...
'  hotness.forEach((v,i) => {\n' ...
'    if(hotSet.has(i)){\n' ...
'      hcG.append("circle").attr("cx",hxScale(i)).attr("cy",hyScale(v)).attr("r",4)\n' ...
'        .attr("fill","#E91E63").attr("stroke","#fff").attr("stroke-width",0.5);\n' ...
'    }\n' ...
'  });\n' ...
'\n' ...
'  // Axis labels\n' ...
'  hcG.append("text").attr("x",chartW/2).attr("y",chartH+25).attr("text-anchor","middle").attr("fill","#555").attr("font-size","10px").text("Time (seconds)");\n' ...
'}\n' ...
'\n' ...
'</script>\n' ...
'</body>\n' ...
'</html>'], dataJSON);
end
